-- phpMyAdmin SQL Dump
-- version 4.7.7
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:3306
-- Tiempo de generación: 19-02-2019 a las 10:14:39
-- Versión del servidor: 5.6.39
-- Versión de PHP: 5.6.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `quottexc_ahpt`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `ImageProductOnly`
--

CREATE TABLE `ImageProductOnly` (
  `id` int(11) NOT NULL,
  `cid` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `operation` varchar(255) DEFAULT NULL,
  `_sms_legal_disclaimer_sms_s_t` varchar(255) DEFAULT NULL,
  `_01_asset_title_sms_s_t` varchar(255) DEFAULT NULL,
  `_02_description_sms_s_t` varchar(255) DEFAULT NULL,
  `_05_asset_language_sms_m_t` varchar(255) DEFAULT NULL,
  `_05_asset_keywords_sms_m_t` text,
  `_11_target_regions_sms_m_t` varchar(255) DEFAULT NULL,
  `_10_target_countries_sms_m_t` text,
  `_04_business_units_sms_m_t` varchar(255) DEFAULT NULL,
  `_13_code_name_sms_s_t` varchar(255) DEFAULT NULL,
  `_sms_submitting_agency_sms_s_t` varchar(255) DEFAULT NULL,
  `_04_hp_owner_sms_s_t` varchar(255) DEFAULT NULL,
  `_24_asset_creator_sms_s_t` varchar(255) DEFAULT NULL,
  `_28_photographer_sms_s_t` varchar(255) DEFAULT NULL,
  `_72_image_orientation_sms_s_t` varchar(255) DEFAULT NULL,
  `_sms_product_color_sms_s_t` varchar(255) DEFAULT NULL,
  `_03_disclosure_level_sms_s_t` varchar(255) DEFAULT NULL,
  `_52_usage_rights_sms_m_t` varchar(255) DEFAULT NULL,
  `_56_rights_holder_sms_s_t` varchar(255) DEFAULT NULL,
  `_sms_usage_restrictions_sms_s_t` varchar(255) DEFAULT NULL,
  `_60_creation_date_sms_s_dt` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `_54_rights_expiration_date_sms_s_dt` varchar(255) DEFAULT NULL,
  `_64_release_date_sms_s_dt` varchar(255) DEFAULT NULL,
  `_62_obsolete_date_sms_s_dt` varchar(255) DEFAULT NULL,
  `_sms_model_release_number_sms_s_t` varchar(255) DEFAULT NULL,
  `_sms_model_release_form_included_sms_s_t` varchar(255) DEFAULT NULL,
  `_sms_restricted_sms_s_t` varchar(255) DEFAULT NULL,
  `_sms_secondary_product_associations_sms_m_t` varchar(255) DEFAULT NULL,
  `_sms_product_hierarchy_inheritance_sms_s_t` varchar(255) DEFAULT NULL,
  `_deployable_flag_sms_s_t` varchar(255) DEFAULT NULL,
  `_81_launch_filename_sms_s_t` varchar(255) DEFAULT NULL,
  `_50_model_reference_numbers_sms_m_t` varchar(255) DEFAULT NULL,
  `_70_image_details_sms_m_t` varchar(255) DEFAULT NULL,
  `_71_image_background_sms_s_t` varchar(255) DEFAULT NULL,
  `_11_asset_subject_sms_s_t` varchar(255) DEFAULT NULL,
  `_restricted_groups_sms_s_t` varchar(255) DEFAULT NULL,
  `_75_ethnicities_sms_m_t` varchar(255) DEFAULT NULL,
  `_77_people_represented_sms_m_t` varchar(255) DEFAULT NULL,
  `_90_legacy_asset_id_sms_s_t` varchar(255) DEFAULT NULL,
  `_legacy_file_name_sms_s_t` varchar(255) DEFAULT NULL,
  `launch_folder_name` varchar(255) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Volcado de datos para la tabla `ImageProductOnly`
--

INSERT INTO `ImageProductOnly` (`id`, `cid`, `name`, `category`, `operation`, `_sms_legal_disclaimer_sms_s_t`, `_01_asset_title_sms_s_t`, `_02_description_sms_s_t`, `_05_asset_language_sms_m_t`, `_05_asset_keywords_sms_m_t`, `_11_target_regions_sms_m_t`, `_10_target_countries_sms_m_t`, `_04_business_units_sms_m_t`, `_13_code_name_sms_s_t`, `_sms_submitting_agency_sms_s_t`, `_04_hp_owner_sms_s_t`, `_24_asset_creator_sms_s_t`, `_28_photographer_sms_s_t`, `_72_image_orientation_sms_s_t`, `_sms_product_color_sms_s_t`, `_03_disclosure_level_sms_s_t`, `_52_usage_rights_sms_m_t`, `_56_rights_holder_sms_s_t`, `_sms_usage_restrictions_sms_s_t`, `_60_creation_date_sms_s_dt`, `_54_rights_expiration_date_sms_s_dt`, `_64_release_date_sms_s_dt`, `_62_obsolete_date_sms_s_dt`, `_sms_model_release_number_sms_s_t`, `_sms_model_release_form_included_sms_s_t`, `_sms_restricted_sms_s_t`, `_sms_secondary_product_associations_sms_m_t`, `_sms_product_hierarchy_inheritance_sms_s_t`, `_deployable_flag_sms_s_t`, `_81_launch_filename_sms_s_t`, `_50_model_reference_numbers_sms_m_t`, `_70_image_details_sms_m_t`, `_71_image_background_sms_s_t`, `_11_asset_subject_sms_s_t`, `_restricted_groups_sms_s_t`, `_75_ethnicities_sms_m_t`, `_77_people_represented_sms_m_t`, `_90_legacy_asset_id_sms_s_t`, `_legacy_file_name_sms_s_t`, `launch_folder_name`) VALUES
(2604, 757, '{91C84C47-FB89-4036-85FC-A9AEE8DF2AB9}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontRight', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontRight.jpg', NULL),
(2605, 757, '{C640453A-77D1-40EC-A5B5-19ECA35B6333}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Stand', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Stand.jpg', NULL),
(2606, 757, '{0A2840E1-B94D-4F76-9E0D-2E0930721924}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tablet', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Top view closed', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tablet.jpg', NULL),
(2607, 757, '{DE437772-2BC7-4BFF-B02D-A391EBECE90C}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tent', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tent.jpg', NULL),
(2608, 757, '{168FEECB-EB7F-4F26-A7C6-69408E556E2F}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontLeft', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Left facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontLeft.jpg', NULL),
(2609, 757, '{7E099A1B-E2D9-4C5F-A443-501275827243}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontOpen', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Center Facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontOpen.jpg', NULL),
(2610, 757, '{66659C14-0A49-478A-99B5-D6C097BA7CC2}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontRight', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontRight.jpg', NULL),
(2611, 757, '{55378599-FF8E-4524-8141-3995A5751153}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Stand', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Stand.jpg', NULL),
(2612, 757, '{87A65077-3624-49AC-89BE-49484CE6B9CD}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tablet', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Top view closed', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tablet.jpg', NULL),
(2613, 757, '{89F2EFA6-4F97-47AF-ABE8-5000DB2AF5C4}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Cadillac|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tent', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Cadillac_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tent.jpg', NULL),
(2614, 757, '{E7FD96DE-F50C-4292-A8B0-493A86631584}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontLeft', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Left facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontLeft.jpg', NULL),
(2615, 757, '{3AB8A4D5-3C6C-413A-9CA3-1230DC416A60}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontOpen', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Center Facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontOpen.jpg', NULL),
(2616, 757, '{0A17C860-524D-41C8-A679-C00F86491BA5}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontRight', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontRight.jpg', NULL),
(2617, 757, '{0C746247-40D8-4749-B07A-42B231C969A3}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Stand', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Stand.jpg', NULL),
(2618, 757, '{E8C3B215-E6B8-47CD-B3D5-7919C48CBA57}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tablet', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Top view closed', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tablet.jpg', NULL),
(2619, 757, '{CF63A9E5-1DB2-42C9-B1AC-63F7E2AC24C9}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tent', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tent.jpg', NULL),
(2620, 757, '{EEB2DFD5-02E3-4587-A406-0A62612DCC34}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontLeft', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Left facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontLeft.jpg', NULL),
(2621, 757, '{8B32F089-D248-4BC0-8369-E95CD05F94AF}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontOpen', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Center Facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontOpen.jpg', NULL),
(2622, 757, '{4E9937DB-50F7-4390-93DE-F1C911B48037}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontRight', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontRight.jpg', NULL),
(2623, 757, '{3630247C-7A73-4A0B-B3A7-654E1FE5FFFC}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Stand', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Stand.jpg', NULL),
(2624, 757, '{5D9E9915-F64C-4024-885B-EF2EDAA1BDB8}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tablet', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Top view closed', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tablet.jpg', NULL),
(2625, 757, '{CBEA3253-6188-49CD-AA6A-59430E8132DE}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 13-inch Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'HP Spectre x360 13-inch Convertible Premium Notebook13, WLAN, Impreza, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'none', 'HP|Spectre|x360|Notebook|13\"|HP Spectre x360 13-inch Premium Notebook|Consumer|Convertible notebook|Convertible PC|Premium Laptop13|WLAN|Impreza|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tent', NULL, NULL, 'PPS CPS', 'Spiderman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Spiderman_13_WLAN_Impreza_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tent.jpg', NULL),
(2626, 759, '{99D7D8FD-6A7F-4CCA-8D58-02373BB1E161}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontLeft', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Left facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontLeft.jpg', NULL),
(2627, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontOpen', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Center Facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontOpen.jpg', NULL),
(2628, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontRight', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontRight.jpg', NULL),
(2629, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Stand', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Stand.jpg', NULL),
(2630, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tablet', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Top view closed', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tablet.jpg', NULL),
(2631, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tent', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tent.jpg', NULL),
(2632, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontLeft', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Left facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontLeft.jpg', NULL),
(2633, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontOpen', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Center Facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontOpen.jpg', NULL),
(2634, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontRight', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontRight.jpg', NULL),
(2635, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Stand', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Stand.jpg', NULL),
(2636, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tablet', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Top view closed', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tablet.jpg', NULL),
(2637, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Cadillac, PoseidonBlue, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Cadillac|PoseidonBlue|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tent', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Cadillac_PoseidonBlue_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tent.jpg', NULL),
(2638, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontLeft', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Left facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontLeft.jpg', NULL),
(2639, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontOpen', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Center Facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontOpen.jpg', NULL),
(2640, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|DarkAshSilver|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontRight', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_DarkAshSilver_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontRight.jpg', NULL),
(2641, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Stand', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Stand', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Stand.jpg', NULL),
(2642, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tablet', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tablet', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Top view closed', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tablet.jpg', NULL),
(2643, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, DarkAshSilver, T, IRcam, nonODD, nonFPR, Win10, CoreSet, Tent', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|DarkAshSilver|T|IRcam|nonODD|nonFPR|Win10|CoreSet|Tent', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing screen center', 'Dark Ash Silver', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_DarkAshSilver_T_IRcam_nonODD_nonFPR_Win10_CoreSet_Tent.jpg', NULL),
(2644, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontLeft', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontLeft', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Left facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontLeft.jpg', NULL),
(2645, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontOpen', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontOpen', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Center Facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontOpen.jpg', NULL),
(2646, 759, '{2E276B79-E7B8-4DB5-9A93-7167CD9CA363}', 'Image - Product Only', NULL, '', '18C2 - HP Spectre x360 15-inch Premium Notebook15, WLAN, ICL-CFL, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'HP Spectre x360 15-inch Convertible Premium Laptop15, WLAN, ICL-CFL, Impreza, PoseidonBlue, T, IRcam, nonODD, FPR, Win10, CoreSet, FrontRight', 'none', 'HP|Spectre|x360|Notebook|15\"|HP Spectre x360 15-inch Premium Notebook|Convertible PC|Convertible Laptop|Premium Laptop|Consumer15|WLAN|ICL-CFL|Impreza|PoseidonBlue|T|IRcam|nonODD|FPR|Win10|CoreSet|FrontRight', NULL, NULL, 'PPS CPS', 'Superman', 'Aniden Interactive', 'laura.stevens1@hp.com', NULL, NULL, 'Right facing', 'Poseidon Blue', 'Public', 'All rights/no restrictions', NULL, '', '2019-01-24 11:42:12', NULL, '10/23/2018', '10/23/2020', NULL, NULL, 'FALSE', '0', 'TRUE', 'TRUE', NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, 'Superman_15_WLAN_ICL-CFL_Impreza_PoseidonBlue_T_IRcam_nonODD_FPR_Win10_CoreSet_FrontRight.jpg', NULL);

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `ImageProductOnly`
--
ALTER TABLE `ImageProductOnly`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `ImageProductOnly`
--
ALTER TABLE `ImageProductOnly`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2647;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
